# Generated by Django 6.0.4 on 2026-04-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flux',
            name='id',
        ),
        migrations.AlterField(
            model_name='flux',
            name='date_time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='date time'),
        ),
    ]
