# Generated by Django 6.0.4 on 2026-04-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(max_length=255)),
                ('end_name', models.CharField(max_length=255)),
                ('start_lng', models.FloatField()),
                ('start_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
